/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#161d1e',
        'on-primary-fixed-variant': '#00530f',
        'slate-gray': '#687A86',
        'secondary-fixed-dim': '#b3c5fd',
        'on-primary-fixed': '#002203',
        'tertiary-fixed-dim': '#a9cbe6',
        secondary: '#4b5d8e',
        'cool-gray': '#949CA9',
        'primary-container': '#28862d',
        'inverse-surface': '#2b3133',
        'on-tertiary-container': '#fcfcff',
        'on-tertiary-fixed': '#001e2f',
        'secondary-container': '#b6c8ff',
        surface: '#f4fafb',
        'on-error-container': '#93000a',
        'inverse-primary': '#7edc77',
        'muted-blue-gray': '#8494A4',
        'on-error': '#ffffff',
        'inverse-on-surface': '#ecf2f3',
        'surface-dim': '#d5dbdc',
        primary: '#006b16',
        'secondary-fixed': '#dae2ff',
        'surface-bright': '#f4fafb',
        'on-primary-container': '#f7fff0',
        'surface-container-highest': '#dee4e5',
        'error-container': '#ffdad6',
        'primary-fixed': '#99f990',
        background: '#f4fafb',
        'on-secondary-container': '#405383',
        'surface-container': '#e9eff0',
        tertiary: '#3f5f77',
        'tertiary-container': '#587891',
        'surface-container-high': '#e3e9ea',
        'on-secondary': '#ffffff',
        'sustainable-green-deep': '#3F933C',
        'on-primary': '#ffffff',
        'on-background': '#161d1e',
        'tertiary-fixed': '#c9e6ff',
        'on-secondary-fixed-variant': '#334574',
        'primary-fixed-dim': '#7edc77',
        'surface-variant': '#dee4e5',
        'surface-container-low': '#eff5f6',
        'surface-tint': '#016e17',
        'on-tertiary-fixed-variant': '#294a61',
        'deep-navy': '#3D5261',
        'surface-container-lowest': '#ffffff',
        'primary-dark': '#16621f',
        error: '#ba1a1a',
        'on-secondary-fixed': '#011847',
        'outline-variant': '#bfcab8',
        outline: '#6f7a6b',
        'on-surface-variant': '#3f4a3c',
        border: '#8494A4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'max-width': '1280px',
      },
      fontFamily: {
        'headline-xl': ['Source Serif 4', 'serif'],
        'headline-xl-mobile': ['Source Serif 4', 'serif'],
        'headline-lg': ['Source Serif 4', 'serif'],
        'headline-md': ['Source Serif 4', 'serif'],
        'headline-sm': ['Source Serif 4', 'serif'],
        'label-md': ['Public Sans', 'sans-serif'],
        'body-md': ['Public Sans', 'sans-serif'],
        'body-lg': ['Public Sans', 'sans-serif'],
        'body-sm': ['Public Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
};
