/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-surface': 'var(--color-on-surface)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'slate-gray': 'var(--color-slate-gray)',
        'secondary-fixed-dim': '#b3c5fd',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'tertiary-fixed-dim': '#a9cbe6',
        secondary: '#4b5d8e',
        'cool-gray': '#949CA9',
        'primary-container': 'var(--color-primary-container)',
        'inverse-surface': '#2b3133',
        'on-tertiary-container': '#fcfcff',
        'on-tertiary-fixed': '#001e2f',
        'secondary-container': '#b6c8ff',
        surface: 'var(--color-surface)',
        'on-error-container': '#93000a',
        'inverse-primary': 'var(--color-primary-fixed-dim)',
        'muted-blue-gray': 'var(--color-slate-gray)',
        'on-error': '#ffffff',
        'inverse-on-surface': '#ecf2f3',
        'surface-dim': 'var(--color-surface-dim)',
        primary: 'var(--color-primary)',
        'secondary-fixed': '#dae2ff',
        'surface-bright': 'var(--color-surface-bright)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'error-container': '#ffdad6',
        'primary-fixed': 'var(--color-primary-fixed)',
        background: 'var(--color-background)',
        'on-secondary-container': '#405383',
        'surface-container': 'var(--color-surface-container)',
        tertiary: '#3f5f77',
        'tertiary-container': '#587891',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-secondary': '#ffffff',
        'sustainable-green-deep': 'var(--color-primary)',
        'on-primary': '#ffffff',
        'on-background': 'var(--color-on-background)',
        'tertiary-fixed': '#c9e6ff',
        'on-secondary-fixed-variant': '#334574',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'surface-variant': 'var(--color-surface-container-highest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-tint': 'var(--color-surface-tint)',
        'on-tertiary-fixed-variant': '#294a61',
        'deep-navy': 'var(--color-deep-navy)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'primary-dark': 'var(--color-primary-dark)',
        error: '#ba1a1a',
        'on-secondary-fixed': '#011847',
        'outline-variant': '#bfcab8',
        outline: '#6f7a6b',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        border: 'var(--color-border)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'max-width': '1280px',
      },
      fontFamily: {
        'headline-xl': ['sans-serif'],
        'headline-xl-mobile': ['sans-serif'],
        'headline-lg': ['sans-serif'],
        'headline-md': ['sans-serif'],
        'headline-sm': ['sans-serif'],
        'label-md': ['sans-serif'],
        'body-md': ['sans-serif'],
        'body-lg': ['sans-serif'],
        'body-sm': ['sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
};
